version: "3.9"

services:
  forum-db:
    image: mysql:latest
    container_name: forum-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: forum
      MYSQL_ROOT_PASSWORD: root
    networks:
      - forum
    volumes:
      - forum:/var/lib/mysql

  forum-cache:
    image: redis:latest
    container_name: forum-cache
    ports:
      - "6379:6379"
    networks:
      - forum
    volumes:
      - forum-cache:/data

  forum:
    image: forum:latest
    container_name: forum
    ports:
      - "3080:8080"
    networks:
      - forum
    depends_on:
      - forum-db
      - forum-cache

networks:
  forum:
    name: forum
    driver: bridge

volumes:
  forum:
    name: forum
    driver: local
  forum-cache:
    name: forum-cache
    driver: local
