spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: liquibase/master.xml
