name: forum-api CI

on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - *

jobs:
  in-docker-tests:
    name: Automated tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Execute tests
        run: ./gradlew test
